name: Backend CI/CD Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build with Maven
        run: mvn clean install
        working-directory: backend  # Ensure this is the correct path to your backend

      - name: Run backend tests
        run: mvn test
        working-directory: backend  # Ensure this is the correct path to your backend

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install
        working-directory: backend/src/main/js  # Ensure this is the correct path to your frontend

      - name: Build frontend
        run: npm run build
        working-directory: backend/src/main/js  # Ensure this is the correct path to your frontend

      - name: Run frontend tests
        run: npm test
        working-directory: backend/src/main/js  # Ensure this is the correct path to your frontend

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3  # Ensures Docker Compose is available

      - name: Build with Docker Compose
        run: docker compose up --build
        